RecipeViewerEvents.removeEntries('item', event => {
    const list = [
        'ytech:tin_ingot',
        'modern_industrialization:steel_block',
        // 'immersiveengineering:ethanol_bucket',
        // 'immersiveengineering:biodiesel_bucket',
        // /immersiveengineering:.*coke.*/,
        // /immersiveengineering:plate.*/,
        // /immersiveengineering:wire.*/,
        // /immersiveengineering:stick.*/,
        // /immersiveengineering:dust.*/,
        // /immersiveengineering:ingot.*/,
        // /immersiveengineering:raw.*/,
        // /immersiveengineering:nugget.*/,
        // /immersiveengineering:.*blast.*/,
        'immersiveengineering:wire_copper',
        'immersiveengineering:wire_electrum',
        'immersiveengineering:wire_aluminum',
        'immersiveengineering:wire_steel',
        'immersiveengineering:wire_lead',
        'ytech:tin_ingot',
        'modern_industrialization:electric_furnace',
        'modern_industrialization:steel_furnace',
        'modern_industrialization:bronze_furnace',
        'extended_industrialization:large_steam_furnace',
        'extended_industrialization:large_electric_furnace',
        'ytech:tin_plate',
        'ytech:lead_plate',
        'ytech:copper_plate',
        'ytech:golden_plate',
        'ytech:bronze_plate',
        'ytech:iron_plate',
        'ytech:bronze_block',
        'ytech:tin_block',
        'ytech:lead_block',
        'ytech:raw_galena_block',
        'ytech:raw_cassiterite_block',
        'ytech:bronze_rod',
        'ytech:tin_rod',
        'ytech:lead_rod',
        'ytech:iron_rod',
        'ytech:golden_rod',
        'ytech:copper_rod',
        'ytech:raw_galena',
        'ytech:raw_cassiterite',
        'ytech:bronze_ingot',
        'ytech:lead_ingot',
        'ytech:crushed_galena',
        'ytech:crushed_cassiterite',
        'ytech:crushed_iron',
        'ytech:crushed_gold',
        'ytech:crushed_copper',
        'ytech:golden_bolt',
        'ytech:copper_bolt',
        'ytech:iron_bolt',
        'ytech:lead_bolt',
        'ytech:tin_bolt',
        'ytech:bronze_bolt',
        'modern_industrialization:netherite_hammer',
        'modern_industrialization:steel_hammer',
        'modern_industrialization:diamond_hammer',
        'modern_industrialization:iron_hammer',
        "modern_industrialization:iron_barrel",
        "modern_industrialization:iron_tank",
        'ytech:cassiterite_gravel_deposit',
        'ytech:golden_gravel_deposit',
        'ytech:nether_iron_ore',
        'ytech:nether_cassiterite_ore',
        'ytech:nether_copper_ore',
        'ytech:nether_galena_ore',
        'ytech:cassiterite_sand_deposit',
        'ytech:golden_sand_deposit',
        'ytech:cassiterite_ore',
        'ytech:galena_ore',
        'ytech:deepslate_cassiterite_ore',
        'ytech:deepslate_galena_ore',
        'occultism:raw_silver',
        'occultism:silver_ingot',
        'occultism:silver_nugget',
        'occultism:silver_dust',
        'occultism:raw_silver_block',
        'occultism:silver_ore',
        'occultism:silver_ore_deepslate',
        'occultism:silver_block',
        'occultism:gold_dust',
        // Admin/system/creative items
        'modopedia:book',
        'guideme:guide',
        'rep_ae2_bridge:quantum',
        'rep_ae2_bridge:living',
        'rep_ae2_bridge:precious',
        'rep_ae2_bridge:metallic',
        'rep_ae2_bridge:ender',
        'rep_ae2_bridge:organic',
        'rep_ae2_bridge:nether',
        'rep_ae2_bridge:earth',
        'amendments:dye_bottle',
        'ftblibrary:icon_item',
        'astages:limit_movement',
        'littlejoys:fishing_spot',
        'littlejoys:dig_spot',
        'mob_weapon_api:laser_gatling',
        'milf:uranium_ore_sample',
        'milf:tungsten_ore_sample',
        'milf:titanium_ore_sample',
        'milf:tin_ore_sample',
        'milf:quartz_ore_sample',
        'milf:salt_ore_sample',
        'milf:platinum_ore_sample',
        'milf:nickel_ore_sample',
        'milf:monazite_ore_sample',
        'milf:lead_ore_sample',
        'milf:iridium_ore_sample',
        'milf:bauxite_ore_sample',
        'milf:antimony_ore_sample',
        'milf:nether_gold_ore_sample',
        'milf:nether_quartz_ore_sample',
        'milf:ancient_debris_ore_sample',
        'milf:redstone_ore_sample',
        'milf:lapis_ore_sample',
        'milf:emerald_ore_sample',
        'milf:coal_ore_sample',
        'milf:copper_ore_sample',
        'milf:diamond_ore_sample',
        'milf:gold_ore_sample',
        'milf:iron_ore_sample',
        'trofers:large_plate',
        'trofers:medium_plate',
        'trofers:small_plate',
        'trofers:large_pillar',
        'trofers:medium_pillar',
        'trofers:small_pillar',
        'lootr:trophy',
        /(?:minecraft|eternal_starlight|ytech|cataclysm|immersiveengineering|spectrum|artifacts|toxony|ribbits):[a-z_]+_spawn_egg|ars_nouveau:[a-z_]+_se|occultism:spawn_egg\/[a-z_]+/,
        /ars_nouveau:[a-z_]+_se/,
        'modern_industrialization:creative_tank',
        'modern_industrialization:creative_storage_unit',
        'modern_industrialization:creative_barrel',
        'ae2:creative_energy_cell',
        'ae2:creative_storage_cell',
        'immersiveengineering:capacitor_creative',
        'replication:creative_memory_chip',
        'tempad:creative_chronometer',
        'ars_nouveau:creative_source_jar',
        'ars_nouveau:creative_spell_book',
        'spectrum:creative_ink_assortment',
        'spectrum:cinderhearth_structure_placer',
        'spectrum:spirit_instiller_structure_placer',
        'spectrum:enchanter_structure_placer',
        'spectrum:fusion_shrine_structure_placer',
        'spectrum:pedestal_tier_3_structure_placer',
        'spectrum:pedestal_tier_2_structure_placer',
        'spectrum:pedestal_tier_1_structure_placer',
        'ars_nouveau:volcanic_sourcelink',
        "enchanted:enchanted_broomstick",
        "toxony:redstone_mortar",
        "apotheosis:potion_charm",
        'apothic_enchanting:flimsy_ender_lead',
        'apothic_enchanting:ender_lead',
        'apothic_enchanting:occult_ender_lead',
        'gag:hearthstone',
        'gag:energized_hearthstone',
        'farmersdelight:flint_knife',
        'hexerei:mahogany_woodcutter',
        'hexerei:willow_woodcutter',
        'hexerei:witch_hazel_woodcutter',
        'ytech:copper_helmet',
        'ytech:copper_chestplate',
        'ytech:copper_leggings',
        'ytech:copper_boots',
        'ytech:bronze_helmet',
        'ytech:bronze_chestplate',
        'ytech:bronze_leggings',
        'ytech:bronze_boots',
        'ytech:bread_dough',
        'ytech:flour',
        'yo_hooks:gold_hook_head',
        'yo_hooks:diamond_hook_head',
        'yo_hooks:netherite_hook_head',
        "apothic_enchanting:scrap_tome",
        "apothic_enchanting:improved_scrap_tome",
        "apothic_enchanting:extraction_tome",
        "apothic_enchanting:ender_library",
        "apothic_enchanting:library",
        "occultism:raw_silver_block",
        "occultism:silver_ingot",
        "occultism:silver_block",
        "occultism:silver_nugget",
        "occultism:raw_silver",
        
        "occultism:silver_nugget",
        
        "malum:copper_nugget",
        /immersiveengineering:storage_.*/,
        /immersiveengineering:dust_.*/,
        /immersiveengineering:raw_.*/,
        /immersiveengineering:nugget_.*/,
        /immersiveengineering:ingot_.*/,
        /immersiveengineering:plate_.*/,
        /immersiveengineering:slab_storage_.*/,
        /immersiveengineering:ore_.*/,
        /immersiveengineering:deepslate_ore_.*/,
        // mod has been temporarily removed
        // "roots:flour",
        // 'roots:silver_nugget', 
        // 'roots:deepslate_silver_ore', 
        // 'roots:silver_ore',
        // "roots:copper_nugget",
        // "roots:raw_silver",
        // "roots:silver_ingot",
        // "roots:silver_block",
        // "roots:raw_silver_block",

        'paganbless:herb_pouch',
        'paganbless:belladonna',
        'paganbless:mandrake_root',
        'paganbless:mandrake_root_plant',
        'paganbless:belladonna_plant',
        'enchanted:belladonna_flower',
        'enchanted:belladonna_seeds',
        'paganbless:hags_taper_plant',
        'paganbless:hag_taper',
        'paganbless:mugwort',
        'paganbless:mugwort_plant',
        'paganbless:imbuing_cauldron',
        'tankstorage:tank_link',
        'bankstorage:bank_link',
        'ars_additions:handy_haversack',
        "waystones:return_scroll",
        "waystones:blank_scroll",
        "waystones:warp_scroll",
        "ars_nouveau:mycelial_sourcelink",
        "ars_nouveau:agronomic_sourcelink",
        "ars_nouveau:vitalic_sourcelink",
        "ars_nouveau:alchemical_sourcelink",
    ]

    list.forEach(item => {
        event.remove(item);
    });
});

RecipeViewerEvents.removeCategories(event => {
    event.remove([
        'modern_industrialization:bronze_furnace',
        'hexeri:woodcutter',
        'paganbless:cauldron_imbuing',
    ]);
});
