ServerEvents.tags('block', event => {

    event.add('ars_nouveau:golem/budding', ["spectrum:budding_topaz", "spectrum:budding_citrine", "spectrum:budding_onyx", "spectrum:budding_moonstone"])
    event.add('ars_nouveau:golem/cluster', ["spectrum:topaz_cluster", "spectrum:citrine_cluster", "spectrum:onyx_cluster", "spectrum:moonstone_cluster"])


})
ServerEvents.tags('item', event => {
    event.add('ars_nouveau:golem/shard', ["spectrum:topaz_shard", "spectrum:citrine_shard", "spectrum:onyx_shard", "spectrum:moonstone_shard"])

    event.add("ars_nouveau:tier_1_glyphs", [
        'ars_nouveau:glyph_prestidigitation', 
        'ars_nouveau:glyph_pull', 
        'ars_nouveau:glyph_redstone_signal', 
        'ars_nouveau:reset', 
        'ars_nouveau:glyph_rotate', 
        'ars_nouveau:glyph_rune', 
        'ars_nouveau:glyph_snare', 
        'ars_elemental:glyph_spark', 
        'ars_nouveau:glyph_light', 
        'ars_elemental:glyph_conjure_terrain', 
        'ars_nouveau:glyph_craft', 
        'ars_nouveau:glyph_cut', 
        'ars_nouveau:glyph_delay', 
        'ars_nouveau:glyph_dispel', 
        'ars_nouveau:glyph_evaporate', 
        'ars_nouveau:glyph_fell', 
        'ars_nouveau:glyph_freeze', 
        'ars_nouveau:glyph_harm', 
        'ars_nouveau:glyph_harvest', 
        'ars_nouveau:glyph_ignite', 
        'ars_nouveau:glyph_interact', 
        'ars_nouveau:glyph_pickup', 
        'ars_nouveau:glyph_gust', 
        'ars_nouveau:glyph_launch', 
        'ars_nouveau:glyph_leap', 
        'ars_nouveau:glyph_place_block', 
        'ars_nouveau:glyph_bubble', 
        'ars_nouveau:glyph_bounce', 
        'ars_nouveau:glyph_phantom_block', 
        'ars_nouveau:glyph_projectile', 
        'ars_nouveau:glyph_pantomime', 
        'ars_nouveau:glyph_break', 
        'ars_nouveau:glyph_underfoot', 
        'ars_nouveau:glyph_touch', 
        'ars_nouveau:glyph_summon_steed',
        'ars_nouveau:glyph_summon_wolves', 
        'ars_nouveau:glyph_toss', 
        'ars_nouveau:glyph_wind_burst', 
        'ars_nouveau:wololo', 
        'ars_nouveau:glyph_amplify', 
        'ars_nouveau:glyph_randomize', 
        'ars_nouveau:glyph_sensitive',
    ])
    event.add("ars_nouveau:tier_2_glyphs", [
        'ars_elemental:glyph_arc_projectile', 
        'ars_nouveau:glyph_ender_inventory', 
        'ars_nouveau:glyph_animate_block', 
        'ars_elemental:glyph_bubble_shield', 
        'ars_elemental:glyph_charm', 
        'ars_nouveau:glyph_cold_snap', 
        'ars_nouveau:glyph_conjure_water', 
        'ars_nouveau:glyph_crush', 
        'ars_elemental:glyph_discharge', 
        'ars_elemental:glyph_envenom', 
        'ars_nouveau:glyph_exchange', 
        'ars_nouveau:glyph_explosion', 
        'ars_nouveau:glyph_firework', 
        'ars_nouveau:glyph_flare', 
        'ars_nouveau:glyph_gravity', 
        'ars_nouveau:glyph_grow', 
        'ars_nouveau:glyph_heal', 
        'ars_nouveau:glyph_infuse', 
        'ars_nouveau:glyph_invisibility', 
        'ars_nouveau:glyph_name', 
        'ars_elemental:glyph_phantom_grasp', 
        'ars_elemental:glyph_poison_spores', 
        'ars_controle:glyph_precise_delay', 
        'ars_nouveau:glyph_slowfall', 
        'ars_nouveau:glyph_smelt', 
        'ars_elemental:glyph_spike', 
        'ars_elemental:glyph_watery_grave', 
        'ars_nouveau:glyph_wind_shear', 
        'ars_elemental:glyph_propagator_arc', 
        'starbunclemania:glyph_pickup_fluid', 
        'starbunclemania:glyph_place_fluid', 
        'ars_nouveau:glyph_sense_magic', 
        'ars_hex:glyph_soul_shatter',
        'ars_nouveau:glyph_aoe', 
        'ars_nouveau:glyph_pierce', 
        'ars_nouveau:glyph_accelerate', 
        'ars_nouveau:glyph_duration_down', 
        'ars_nouveau:glyph_dampen', 
        'ars_nouveau:glyph_decelerate', 
        'ars_nouveau:glyph_extend_time', 
        'ars_nouveau:glyph_extract', 
        'ars_nouveau:glyph_fortune',
        'ars_elemental:glyph_mist', 
        'ars_elemental:glyph_geyser', 
        'ars_elemental:glyph_slip_feet', 
        'ars_elemental:glyph_summon_bee', 
        'ars_elemental:glyph_summon_slime',
    ])
    event.add("ars_nouveau:tier_3_glyphs", [
        'ars_elemental:glyph_homing_projectile', 
        'ars_additions:glyph_recall', 
        'ars_additions:glyph_retaliate', 
        'ars_nouveau:glyph_blink', 
        'ars_nouveau:glyph_burst', 
        'ars_elemental:glyph_conflagrate', 
        'ars_nouveau:glyph_fangs', 
        'ars_nouveau:glyph_glide', 
        'ars_nouveau:glyph_hex', 
        'ars_nouveau:glyph_intangible', 
        'ars_elemental:glyph_life_link', 
        'ars_nouveau:glyph_lightning', 
        'ars_nouveau:glyph_linger', 
        'ars_additions:glyph_mark', 
        'ars_elemental:glyph_nullify_defense', 
        'ars_nouveau:glyph_orbit', 
        'ars_nouveau:rewind', 
        'ars_nouveau:glyph_summon_decoy', 
        'ars_nouveau:glyph_summon_undead', 
        'ars_nouveau:glyph_summon_vex', 
        'ars_nouveau:glyph_wall', 
        'ars_nouveau:glyph_wither', 
        'ars_elemental:glyph_propagator_homing', 
        'ars_nouveau:glyph_split',
        'ars_elemental:glyph_cauterize',
        'ars_elemental:glyph_cavitate',
        'ars_elemental:glyph_oxidize',
        'ars_elemental:glyph_rage',
        'ars_elemental:glyph_water_jet',
    ])

    event.add('ars_nouveau:horn_food', [
        'arsdelight:mendosteen_hornbeer', 
        'arsdelight:bastion_hornbeer', 
        'arsdelight:bombegrante_hornbeer', 
        'arsdelight:frostaya_hornbeer', 
        'arsdelight:source_berry_hornbeer'
    ])
})

ServerEvents.tags("entity_type", event => {
    event.add("ars_nouveau:drygmy_blacklist", "#c:bosses")
    event.add("ars_nouveau:jar_blacklist", "#c:bosses")
})



