// Create constant list for work with regular expression
const list = [
	'ytech:tin_ingot',
	'modern_industrialization:steel_block',
	// 'immersiveengineering:ethanol_bucket',
	// 'immersiveengineering:biodiesel_bucket',
	// /immersiveengineering:.*coke.*/,
	// /immersiveengineering:plate.*/,
	// /immersiveengineering:wire.*/,
	// /immersiveengineering:stick.*/,
	// /immersiveengineering:dust.*/,
	// /immersiveengineering:ingot.*/,
	// /immersiveengineering:raw.*/,
	// /immersiveengineering:nugget.*/,
	// /immersiveengineering:.*blast.*/,
	'immersiveengineering:wire_copper',
	'immersiveengineering:wire_electrum',
	'immersiveengineering:wire_aluminum',
	'immersiveengineering:wire_steel',
	'immersiveengineering:wire_lead',
	'ytech:tin_ingot',
	'modern_industrialization:electric_furnace',
	'modern_industrialization:steel_furnace',
	'modern_industrialization:bronze_furnace',
	'ytech:tin_plate',
	'ytech:lead_plate',
	'ytech:copper_plate',
	'ytech:golden_plate',
	'ytech:bronze_plate',
	'ytech:iron_plate',
	'ytech:bronze_block',
	'ytech:tin_block',
	'ytech:lead_block',
	'ytech:raw_galena_block',
	'ytech:raw_cassiterite_block',
	'ytech:bronze_rod',
	'ytech:tin_rod',
	'ytech:lead_rod',
	'ytech:iron_rod',
	'ytech:golden_rod',
	'ytech:copper_rod',
	'ytech:raw_galena',
	'ytech:raw_cassiterite',
	'ytech:bronze_ingot',
	'ytech:lead_ingot',
	'ytech:crushed_galena',
	'ytech:crushed_cassiterite',
	'ytech:crushed_iron',
	'ytech:crushed_gold',
	'ytech:crushed_copper',
	'ytech:golden_bolt',
	'ytech:copper_bolt',
	'ytech:iron_bolt',
	'ytech:lead_bolt',
	'ytech:tin_bolt',
	'ytech:bronze_bolt',
	'modern_industrialization:netherite_hammer',
	'modern_industrialization:steel_hammer',
	'modern_industrialization:diamond_hammer',
	'modern_industrialization:iron_hammer',
	'ytech:cassiterite_gravel_deposit',
	'ytech:golden_gravel_deposit',
	'ytech:nether_iron_ore',
	'ytech:nether_cassiterite_ore',
	'ytech:nether_copper_ore',
	'ytech:nether_galena_ore',
	'ytech:cassiterite_sand_deposit',
	'ytech:golden_sand_deposit',
	'ytech:cassiterite_ore',
	'ytech:galena_ore',
	'ytech:deepslate_cassiterite_ore',
	'ytech:deepslate_galena_ore',
	'occultism:raw_silver',
	'occultism:silver_ingot',
	'occultism:silver_nugget',
	'occultism:silver_dust',
	'occultism:raw_silver_block',
	'occultism:silver_ore',
	'occultism:silver_ore_deepslate',
	'occultism:silver_block',
	'occultism:gold_dust',
	// Admin/system/creative items
	'modopedia:book',
	'guideme:guide',
	'apothic_compats:ornate_ring',
	'apothic_compats:ornamented_necklace',
	'apothic_compats:head_cover',
	'apothic_compats:showy_gloves',
	'apothic_compats:adorned_boots',
	'apothic_compats:embellished_curio',
	'apothic_compats:fancy_charm',
	'apothic_compats:flashy_bracelet',
	'apothic_compats:body_chain',
	'apothic_compats:florid_belt',
	'apothic_compats:back_plate',
	'rep_ae2_bridge:quantum',
	'rep_ae2_bridge:living',
	'rep_ae2_bridge:precious',
	'rep_ae2_bridge:metallic',
	'rep_ae2_bridge:ender',
	'rep_ae2_bridge:organic',
	'rep_ae2_bridge:nether',
	'rep_ae2_bridge:earth',
	'amendments:dye_bottle',
	'ftblibrary:icon_item',
	'astages:limit_movement',
	'littlejoys:fishing_spot',
	'littlejoys:dig_spot',
	'databank:megastructure_save',
	'mob_weapon_api:laser_gatling',
	'kubejs:uranium_ore_sample',
	'kubejs:tungsten_ore_sample',
	'kubejs:titanium_ore_sample',
	'kubejs:tin_ore_sample',
	'kubejs:quartz_ore_sample',
	'kubejs:salt_ore_sample',
	'kubejs:platinum_ore_sample',
	'kubejs:nickel_ore_sample',
	'kubejs:monazite_ore_sample',
	'kubejs:lead_ore_sample',
	'kubejs:iridium_ore_sample',
	'kubejs:bauxite_ore_sample',
	'kubejs:antimony_ore_sample',
	'kubejs:nether_gold_ore_sample',
	'kubejs:nether_quartz_ore_sample',
	'kubejs:ancient_debris_ore_sample',
	'kubejs:redstone_ore_sample',
	'kubejs:lapis_ore_sample',
	'kubejs:emerald_ore_sample',
	'kubejs:coal_ore_sample',
	'kubejs:copper_ore_sample',
	'kubejs:diamond_ore_sample',
	'kubejs:gold_ore_sample',
	'kubejs:iron_ore_sample',
	'trofers:large_plate',
	'trofers:medium_plate',
	'trofers:small_plate',
	'trofers:large_pillar',
	'trofers:medium_pillar',
	'trofers:small_pillar',
	'lootr:trophy',
	/(?:minecraft|eternal_starlight|ytech|cataclysm|immersiveengineering|pastel|artifacts|toxony|ribbits):[a-z_]+_spawn_egg|ars_nouveau:[a-z_]+_se|occultism:spawn_egg\/[a-z_]+/,
	/ars_nouveau:[a-z_]+_se/,
	'modern_industrialization:creative_tank',
	'modern_industrialization:creative_storage_unit',
	'modern_industrialization:creative_barrel',
	'ae2:creative_energy_cell',
	'ae2:creative_storage_cell',
	'immersiveengineering:capacitor_creative',
	'replication:creative_memory_chip',
	'tempad:creative_chronometer',
	'ars_nouveau:creative_source_jar',
	'ars_nouveau:creative_spell_book',
	'nautec:creative_power_source',
	'pastel:creative_ink_assortment',
	'pastel:cinderhearth_structure_placer',
	'pastel:spirit_instiller_structure_placer',
	'pastel:enchanter_structure_placer',
	'pastel:fusion_shrine_structure_placer',
	'pastel:pedestal_tier_3_structure_placer',
	'pastel:pedestal_tier_2_structure_placer',
	'pastel:pedestal_tier_1_structure_placer',
	'ars_nouveau:volcanic_sourcelink',
	"enchanted:enchanted_broomstick",
	"toxony:redstone_mortar",
	"apotheosis:potion_charm",
	'apothic_enchanting:flimsy_ender_lead',
	'apothic_enchanting:ender_lead',
	'apothic_enchanting:occult_ender_lead',
	'gag:hearthstone',
	'gag:energized_hearthstone',
	'farmersdelight:flint_knife',
]

// Hide items
RecipeViewerEvents.removeEntries('item', event => {
	event.remove(list)
})
