
const born_in_chaos_mobs = [
    { id: "decrepit_skeleton", mob: "born_in_chaos_v1:decrepit_skeleton" },
    { id: "baby_skeleton", mob: "born_in_chaos_v1:baby_skeleton" },
    { id: "bone_imp", mob: "born_in_chaos_v1:bone_imp" },
    { id: "siamese_skeletons", mob: "born_in_chaos_v1:siamese_skeletons" },
    { id: "skeleton_thrasher", mob: "born_in_chaos_v1:skeleton_thrasher" },
    { id: "bonescaller", mob: "born_in_chaos_v1:bonescaller" },
    { id: "supreme_bonescaller", mob: "born_in_chaos_v1:supreme_bonescaller" },
    { id: "spirit_guide", mob: "born_in_chaos_v1:spirit_guide" },
    { id: "lifestealer", mob: "born_in_chaos_v1:lifestealer" },
    { id: "decaying_zombie", mob: "born_in_chaos_v1:decaying_zombie" },
    { id: "barrel_zombie", mob: "born_in_chaos_v1:barrel_zombie" },
    { id: "door_knight", mob: "born_in_chaos_v1:door_knight" },
    { id: "zombie_clown", mob: "born_in_chaos_v1:zombie_clown" },
    { id: "zombie_fisherman", mob: "born_in_chaos_v1:zombie_fisherman" },
    { id: "zombie_bruiser", mob: "born_in_chaos_v1:zombie_bruiser" },
    { id: "fallen_chaos_knight", mob: "born_in_chaos_v1:fallen_chaos_knight" },
    { id: "maggot", mob: "born_in_chaos_v1:maggot" },
    { id: "corpse_fly", mob: "born_in_chaos_v1:corpse_fly" },
    { id: "bloody_gadfly", mob: "born_in_chaos_v1:bloody_gadfly" },
    { id: "swarmer", mob: "born_in_chaos_v1:swarmer" },
    { id: "firelight", mob: "born_in_chaos_v1:firelight" },
    { id: "baby_spider", mob: "born_in_chaos_v1:baby_spider" },
    { id: "mother_spider", mob: "born_in_chaos_v1:mother_spider" },
    { id: "dread_hound", mob: "born_in_chaos_v1:dread_hound" },
    { id: "dire_hound_leader", mob: "born_in_chaos_v1:dire_hound_leader" },
    { id: "thornshell_crab", mob: "born_in_chaos_v1:thornshell_crab" },
    { id: "corpse_fish", mob: "born_in_chaos_v1:corpse_fish" },
    { id: "glutton_fish", mob: "born_in_chaos_v1:glutton_fish" },
    { id: "restless_spirit", mob: "born_in_chaos_v1:restless_spirit" },
    { id: "scarlet_persecutor", mob: "born_in_chaos_v1:scarlet_persecutor" },
    { id: "phantom_creeper", mob: "born_in_chaos_v1:phantom_creeper" },
    { id: "dark_vortex", mob: "born_in_chaos_v1:dark_vortex" },
    { id: "spiritof_chaos", mob: "born_in_chaos_v1:spiritof_chaos" },
    { id: "nightmare_stalker", mob: "born_in_chaos_v1:nightmare_stalker" },
    { id: "missioner", mob: "born_in_chaos_v1:missioner" },
    { id: "pumpkin_spirit", mob: "born_in_chaos_v1:pumpkin_spirit" },
    { id: "seared_spirit", mob: "born_in_chaos_v1:seared_spirit" },
    { id: "krampus", mob: "born_in_chaos_v1:krampus" },
    { id: "krampus_henchman", mob: "born_in_chaos_v1:krampus_henchman" },
    { id: "mr_pumpkin", mob: "born_in_chaos_v1:mr_pumpkin" },
    { id: "sir_pumpkinhead", mob: "born_in_chaos_v1:sir_pumpkinhead" },
    { id: "senor_pumpkin", mob: "born_in_chaos_v1:senor_pumpkin" },
    { id: "lord_pumpkinhead", mob: "born_in_chaos_v1:lord_pumpkinhead" },
    { id: "infernal_spirit", mob: "born_in_chaos_v1:infernal_spirit" },
    { id: "pumpkin_dunce", mob: "born_in_chaos_v1:pumpkin_dunce" },
    { id: "mrs_pumpkin", mob: "born_in_chaos_v1:mrs_pumpkin" },
    { id: "pumpkin_bruiser", mob: "born_in_chaos_v1:pumpkin_bruiser" },
    { id: "skeleton_demoman", mob: "born_in_chaos_v1:skeleton_demoman" },
    { id: "spirit_guide_assistant", mob: "born_in_chaos_v1:spirit_guide_assistant" },
    { id: "zombie_lumberjack", mob: "born_in_chaos_v1:zombie_lumberjack" },
]

mobRestriction("born_in_chaos_v1", born_in_chaos_mobs)
