const minecraft_mobs = [
    {id:"creeper", mob: "minecraft:creeper"},
    {id:"zombie", mob: "minecraft:zombie"},
    {id:"zombie_villager", mob: "minecraft:zombie_villager"},
    {id:"enderman", mob: "minecraft:enderman"},
    {id:"spider", mob: "minecraft:spider"},
    {id:"slime", mob: "minecraft:slime"},
    {id:"skeleton", mob: "minecraft:skeleton"},
    {id:"witch", mob: "minecraft:witch"},
    {id:"pillager", mob: "minecraft:pillager"},
    {id:"phantom", mob: "minecraft:phantom"},
    {id:"stray", mob: "minecraft:stray"},
    {id:"husk", mob: "minecraft:husk"},
    {id:"bogged", mob: "minecraft:bogged"},
    {id:"drowned", mob: "minecraft:drowned"},
    {id:"wandering_trader", mob: "minecraft:wandering_trader"},
    {id:"cave_spider", mob: "minecraft:cave_spider"},
    {id:"wither_skeleton", mob: "minecraft:wither_skeleton"},
    {id:"ravager", mob: "minecraft:ravager"},
    {id:"vex", mob: "minecraft:vex"},
    {id:"hoglin", mob: "minecraft:hoglin"},
    {id:"zombified_piglin", mob: "minecraft:zombified_piglin"},
    {id:"piglin", mob: "minecraft:piglin"},
    {id:"ghast", mob: "minecraft:ghast"},
    {id:"magma_cube", mob: "minecraft:magma_cube"},
    {id:"blaze", mob: "minecraft:blaze"},
    {id:"shulker", mob: "minecraft:shulker"},
]

mobRestriction("minecraft", minecraft_mobs)